# Generated by Django 4.2.7 on 2024-06-15 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vote', '0005_remove_ward_constituency_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('registration_number', models.CharField(default=None, max_length=10)),
                ('email', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('votes', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.election')),
            ],
        ),
        migrations.AddField(
            model_name='voter',
            name='election',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vote.election'),
            preserve_default=False,
        ),
    ]
