# Generated by Django 5.0.6 on 2024-06-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_election_candidate_voter_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
