# Generated by Django 5.0.6 on 2024-06-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_candidate_user_voter_user_alter_candidate_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.AddField(
            model_name='candidate',
            name='id',
            field=models.BigAutoField(auto_created=True, default=99, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
