# Generated by Django 5.0.6 on 2024-06-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_remove_candidate_user_candidate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
